version: '3.3'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:

networks:
  default:
    name: stellar_default